---
application:
  name: "movies-vidly"
  project: "test"
  organization: "QoveryCommunity"
  storage:
  - name: "hmm"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/hmm"
routers:
- name: "main-movies-vidly"
  routes:
  - application_name: "movies-vidly"
    paths:
    - "/*"
